web:
  build: .
  command: python /assignment_1/app/app.py
  ports:
   - "5000:5000"
  volumes:
   - .:/assi
  links:
   - db
  hostname: myappserver
db:
  hostname: mysqlserver
  image: orchardup/mysql
  environment:
     MYSQL_ROOT_PASSWORD: pavan
     MYSQL_DATABASE: wordpress